"""Add venue location FKs

Revision ID: 4a50760a79ae
Revises: 0b0180d06029
Create Date: 2020-05-13 06:57:34.051788

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a50760a79ae'
down_revision = '0b0180d06029'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('city', sa.Column('state_id', sa.Integer(), nullable=False))
    op.drop_constraint('city_state_code_fkey', 'city', type_='foreignkey')
    op.create_foreign_key(None, 'city', 'state', ['state_id'], ['id'])
    op.drop_column('city', 'state_code')
    op.add_column('venue', sa.Column('city_id', sa.Integer(), nullable=False))
    op.add_column('venue', sa.Column('state_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'venue', 'state', ['state_id'], ['id'])
    op.create_foreign_key(None, 'venue', 'city', ['city_id'], ['id'])
    op.drop_column('venue', 'city')
    op.drop_column('venue', 'state')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venue', sa.Column('state', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.add_column('venue', sa.Column('city', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'venue', type_='foreignkey')
    op.drop_constraint(None, 'venue', type_='foreignkey')
    op.drop_column('venue', 'state_id')
    op.drop_column('venue', 'city_id')
    op.add_column('city', sa.Column('state_code', sa.VARCHAR(length=2), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'city', type_='foreignkey')
    op.create_foreign_key('city_state_code_fkey', 'city', 'state', ['state_code'], ['state_code'])
    op.drop_column('city', 'state_id')
    # ### end Alembic commands ###
