"""empty message

Revision ID: 87718d2c6907
Revises: 93722d1f6db9
Create Date: 2020-05-13 21:24:42.319379

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '87718d2c6907'
down_revision = '93722d1f6db9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('show', sa.Column('date_time', sa.DateTime(), nullable=False))
    op.drop_column('show', 'date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('show', sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('show', 'date_time')
    # ### end Alembic commands ###
