"""Remove state city FKs

Revision ID: d89d6af9abfc
Revises: fd247c6e0289
Create Date: 2020-05-13 21:19:51.537721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd89d6af9abfc'
down_revision = 'fd247c6e0289'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('city', sa.String(length=120), nullable=True))
    op.add_column('artist', sa.Column('state', sa.String(length=120), nullable=True))
    op.drop_constraint('artist_city_id_fkey', 'artist', type_='foreignkey')
    op.drop_constraint('artist_state_id_fkey', 'artist', type_='foreignkey')
    op.drop_column('artist', 'state_id')
    op.drop_column('artist', 'city_id')
    op.add_column('venue', sa.Column('city', sa.String(length=120), nullable=True))
    op.add_column('venue', sa.Column('state', sa.String(length=120), nullable=True))
    op.drop_constraint('venue_state_id_fkey', 'venue', type_='foreignkey')
    op.drop_constraint('venue_city_id_fkey', 'venue', type_='foreignkey')
    op.drop_column('venue', 'state_id')
    op.drop_column('venue', 'city_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venue', sa.Column('city_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('venue', sa.Column('state_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('venue_city_id_fkey', 'venue', 'city', ['city_id'], ['id'])
    op.create_foreign_key('venue_state_id_fkey', 'venue', 'state', ['state_id'], ['id'])
    op.drop_column('venue', 'state')
    op.drop_column('venue', 'city')
    op.add_column('artist', sa.Column('city_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('artist', sa.Column('state_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('artist_state_id_fkey', 'artist', 'state', ['state_id'], ['id'])
    op.create_foreign_key('artist_city_id_fkey', 'artist', 'city', ['city_id'], ['id'])
    op.drop_column('artist', 'state')
    op.drop_column('artist', 'city')
    # ### end Alembic commands ###
