"""Add location FKs to Artist model

Revision ID: de0ad1947189
Revises: 7a28aa2562c6
Create Date: 2020-05-13 07:20:29.221562

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de0ad1947189'
down_revision = '7a28aa2562c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('city_id', sa.Integer(), nullable=False))
    op.add_column('artist', sa.Column('state_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'artist', 'state', ['state_id'], ['id'])
    op.create_foreign_key(None, 'artist', 'city', ['city_id'], ['id'])
    op.drop_column('artist', 'genres')
    op.drop_column('artist', 'state')
    op.drop_column('artist', 'city')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('city', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.add_column('artist', sa.Column('state', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.add_column('artist', sa.Column('genres', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'artist', type_='foreignkey')
    op.drop_constraint(None, 'artist', type_='foreignkey')
    op.drop_column('artist', 'state_id')
    op.drop_column('artist', 'city_id')
    # ### end Alembic commands ###
